spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true

  jackson:
    default-property-inclusion: non_null

security:
  jwt:
    token:
      secret-key: accessKey
      refresh-key: refreshKey
